#Force users to change password at first login
---
- name: For New Users
  hosts: all
  gather_facts: false
  tasks:
     - name: Force user "username1" to change the password
       remote_user: ansible-client
       become: yes
       become_method: sudo 
       command: 
           chage -d 0 username1

     - name: Force user "username2" to change the password # You must add this section to get the exact number of user you create
       remote_user: ansible-client
       become: yes
       become_method: sudo 
       command: 
           chage -d 0 username2
...